### ISSUE TITLE
Drivebase boilerplate

### ISSUE THREAD

**Issue by Jayden-Boomer** [Comet-Robotics/vex-2025#1]
I want to get rid of a bunch of boilerplate in Drivebase.cpp by having it inherit from lemlib::Chassis since all it's really doing is wrapping that class anyway. I'm not sure if there was a reason we have it that way / a reason against changing it.

**Comment by kevalshah2005** [comment]
Yeah sure, go ahead! I just don't really know how to make it work in C++
